baseurl = "/"
host = "https:/mods.pages.dev"
title = "Manfred Costa Blanca Homes"
relativeURLs = true

[[module.imports]]
    path="github.com/manfredcostahomes/property"
    disabled=false
[[module.imports.mounts]]
    source="contents/"
    target="contents/"

[taxonomies]
  home = "homes"

[outputs]
    page = ["json","html"]
    section = ["json"] 
    home = ["json","html"]
    contact = ["html"]
    policy = ["html"]


